mp.openapi.extensions.smallrye.security-schemes=BearerAuth
mp.openapi.extensions.smallrye.security-schemes.BearerAuth.type=http
mp.openapi.extensions.smallrye.security-schemes.BearerAuth.scheme=bearer
mp.openapi.extensions.smallrye.security-schemes.BearerAuth.bearer-format=JWT

quarkus.http.port=8080

quarkus.rest-client.ms-auth.url=http://localhost:8081
quarkus.rest-client.ms-users.url=http://localhost:8082

quarkus.swagger-ui.always-include=true
